# Netlify configuration for Production

[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"

# Redirect rule for the API
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
